SET SESSION_DATE=20180917
SET AUTOENCODER_DIM=128
SET IC_DIM=32
SET BATCH_SIZE=16
SET WEIGHT_INCREASE_STEPS=2000
SET DEVICE=cpu
SET KEEP_FACTOR=0.85
SET NUM_FACTORS=32


for %%L in (500, 2000) do (
    lfads_singlesession %SESSION_DATE% %NUM_FACTORS% %AUTOENCODER_DIM% %IC_DIM% %BATCH_SIZE% %WEIGHT_INCREASE_STEPS% %KEEP_FACTOR% %AUTOENCODER_DIM% %DEVICE% %%L
)

