SET SESSION_DATE=20180917
SET AUTOENCODER_DIM=64
SET IC_DIM=32
SET BATCH_SIZE=16
SET WEIGHT_INCREASE_STEPS=2000
SET DEVICE=gpu
SET KEEP_FACTOR=0.85
SET NUM_FACTORS=20


extended_window_lfads_singlesession %SESSION_DATE% %NUM_FACTORS% %AUTOENCODER_DIM% %IC_DIM% %BATCH_SIZE% %WEIGHT_INCREASE_STEPS% 0.85 %AUTOENCODER_DIM% %DEVICE%
